### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by screret** [NemEzanevem/VendingMachine-Fabric#2]
- [ ] basic functionality of buying items with emeralds etc (payment item changeable in config)
- [ ] 1024-size stacks in vending machine
- [ ] money
- [ ] money converter (changes money type to higher/lower
- [ ] wallet
- [ ] buying things with money
